ARG BASE_VERSION
FROM strapi/base:${BASE_VERSION}

ARG STRAPI_VERSION
RUN npm global add @strapi/strapi@${STRAPI_VERSION}

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY docker-entrypoint-dev.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint-dev.sh 
ENTRYPOINT ["docker-entrypoint-dev.sh"]

CMD ["strapi", "develop"]