version: "3"

services:
  strapi:
    # image: strapi/strapi
    build: 
      context: .
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4.0.3
    container_name: bee-news-strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_PORT_PROD: ${DATABASE_PORT}
      DATABASE_USERNAME_PROD: ${DATABASE_USERNAME}
      DATABASE_PASSWORD_PROD: ${DATABASE_PASSWORD}
      DATABASE_HOST_PROD: ${DATABASE_HOST}
      DATABASE_NAME_PROD: ${DATABASE_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:${PORT}"
    depends_on:
      - db

  db:
    container_name: bee-news-mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
