version: "3.3"

services:
  strapi:
    # image: strapi/strapi
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4.1.12
    container_name: bee-news-strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CHARSET: ${DATABASE_CHARSET}
      DATABASE_SSL: ${DATABASE_SSL}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:${PORT}"
networks:
  default:
    external: true
    name: btree-docker-mysql_btree-maria-network