FROM strapi/base:latest

ARG STRAPI_VERSION
RUN yarn global add @strapi/strapi@4.0.4

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app
ADD app .

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh 
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["yarn", "start"]