version: "3"

services:
  strapi:
    # image: strapi/strapi
    build: 
      context: ./docker-dev
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4.0.4
    container_name: bee-news-strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CHARSET: ${DATABASE_CHARSET}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:${PORT}"
    depends_on:
      - db

  db:
    container_name: bee-news-mysql
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "33061:3306"
