FROM node:16-alpine
RUN apk add --no-cache libc6-compat yarn
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY docker-entrypoint-dev.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint-dev.sh 
ENTRYPOINT ["docker-entrypoint-dev.sh"]

CMD ["strapi", "develop"]